Repository Kenny2github/Report, pull requests merged in 2021-05, with the labels that each got.

#8 added paging to the handled reports page
  SpecialHandleReports.php
  i18n/en.json
Labels: enhancement

#11 add translation for Turkish
  Report.i18n.alias.php
  i18n/tr.json
Labels: i18n, prgtm

#10 Replaces usages of deprecated Revision::newFromId and User::newFromId
  includes/HandleReportsPager.php
  includes/SpecialHandleReports.php
  includes/SpecialReport.php
Labels: prgtm
